### ISSUE TITLE
RDP port already in use

### ISSUE THREAD

**Issue by Progra-MMO** [dockur/windows#542]
### Operating system

Fedora 39

### Description

Hello, I'm trying to start the container but ran with an error that says that port 3389 is already in use. In fact it is because I am usin XRDP on fedora. 
`Creating windows ... error

ERROR: for windows  Cannot start service windows: driver failed programming external connectivity on endpoint windows (c36817bc37ddd91fa913d77cda74fe5dea6bdb29b0002f660269a10af3082baf): Error starting userland proxy: listen tcp4 0.0.0.0:3389: bind: address already in use

ERROR: for windows  Cannot start service windows: driver failed programming external connectivity on endpoint windows (c36817bc37ddd91fa913d77cda74fe5dea6bdb29b0002f660269a10af3082baf): Error starting userland proxy: listen tcp4 0.0.0.0:3389: bind: address already in use
`

Then I tryed to replace the RDP port for 3390 and the compose yaml and this error appears

`Recreating windows ... 

ERROR: for windows  'ContainerConfig'

ERROR: for windows  'ContainerConfig'
Traceback (most recent call last):
  File "/bin/docker-compose", line 33, in <module>
    sys.exit(load_entry_point('docker-compose==1.29.2', 'console_scripts', 'docker-compose')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/usr/lib/python3.12/site-packages/compose/cli/main.py", line 203, in perform_command
    handler(command, command_options)
  File "/usr/lib/python3.12/site-packages/compose/metrics/decorator.py", line 18, in wrapper
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/compose/cli/main.py", line 1186, in up
    to_attach = up(False)
                ^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/compose/cli/main.py", line 1166, in up
    return self.project.up(
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/compose/project.py", line 697, in up
    results, errors = parallel.parallel_execute(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/compose/parallel.py", line 108, in parallel_execute
    raise error_to_reraise
  File "/usr/lib/python3.12/site-packages/compose/parallel.py", line 206, in producer
    result = func(obj)
             ^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/compose/project.py", line 679, in do
    return service.execute_convergence_plan(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/compose/service.py", line 579, in execute_convergence_plan
    return self._execute_convergence_recreate(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/compose/service.py", line 499, in _execute_convergence_recreate
    containers, errors = parallel_execute(
                         ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/compose/parallel.py", line 108, in parallel_execute
    raise error_to_reraise
  File "/usr/lib/python3.12/site-packages/compose/parallel.py", line 206, in producer
    result = func(obj)
             ^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/compose/service.py", line 494, in recreate
    return self.recreate_container(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/compose/service.py", line 612, in recreate_container
    new_container = self.create_container(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/compose/service.py", line 330, in create_container
    container_options = self._get_container_create_options(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/compose/service.py", line 921, in _get_container_create_options
    container_options, override_options = self._build_container_volume_options(
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/compose/service.py", line 960, in _build_container_volume_options
    binds, affinity = merge_volume_bindings(
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/compose/service.py", line 1548, in merge_volume_bindings
    old_volumes, old_mounts = get_container_data_volumes(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/compose/service.py", line 1579, in get_container_data_volumes
    container.image_config['ContainerConfig'].get('Volumes') or {}
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'ContainerConfig'
`

Should I do another thing on the configuration in order to make this works?

I found this link https://learn.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/change-listening-port where probably should change the listening port in the registry, but I don't know how to do it on the docker compose file.



### Docker compose

ervices:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "win7"
      LANGUAGE: "Spanish"
      REGION: "es-AR"
      KEYBOARD: "es-AR"
      DISK_SIZE: "100G"
    volumes:
      - /home/user/Documentos/WINDON:/storage
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3390:3389/tcp
      - 3390:3389/udp


### Docker log

Error response from daemon: No such container: windows

### Screenshots (optional)

_No response_

**Comment by Progra-MMO** [comment]
Thank you kroese, the problem was that i was using docker-compose up instead of docker compose up. After tryed the last one the container started correctly! Thank you very much!

**Comment by Progra-MMO** [comment]
Thank you kroese, the problem was that i was using docker-compose up instead of docker compose up. After tryed the last one the container started correctly! Thank you very much!
